### ISSUE TITLE
Mining VK Wandering Ore hard-crashes the server

### ISSUE THREAD

**Issue by SakulFlee** [OpenPlayVerse/ProjectCreate#3]
Mining VK Wandering Ore hard-crashes the server.
After some attempts, the Ore block disappears, but no drop can be found.

**Comment by Namelessys** [comment]
I could find that such bugs appear but there seems to be no solution. Also the VK mod seems to be pretty unstable all in one from what i've read so far, especially on servers. That most of the issue "tracking" happens on their discord server and not in an actuall issue tracker makes troubleshooting those things not more easy...

We'll remove VK and clockwork for the time being since it gets more stable.
